# Python-for-Android Configuration for Turbo Notes
# This replaces the buildozer.spec file

[app]
title = "Turbo Notes"
package = "com.turbo.notes"
version = "1.0.0"
orientation = "portrait"

[build]
bootstrap = "sdl2"
requirements = [
    "python3",
    "kivy==2.2.1", 
    "kivymd==1.1.1",
    "pillow",
    "pygments", 
    "plyer",
    "android",
    "pyjnius"
]
architectures = ["arm64-v8a", "armeabi-v7a"]
ndk_api = 21
copy_libs = true

[android]
permissions = [
    "INTERNET",
    "WRITE_EXTERNAL_STORAGE", 
    "READ_EXTERNAL_STORAGE",
    "WAKE_LOCK",
    "VIBRATE"
]
private_storage = true

[metadata]
author = "Turbo Notes Team"
description = "Lightweight, developer-friendly note and task management app" 