name: Build Android APK

on:
  push:
    branches: [ master, main, develop ]
    paths:
      - 'TurboNotesAndroid/**'
      - '.github/workflows/android-build.yml'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'TurboNotesAndroid/**'
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        default: 'debug'
        type: choice
        options:
        - debug
        - release

# Add permissions for GitHub token
permissions:
  contents: write
  packages: write
  actions: read

env:
  ANDROID_APP_PATH: ./TurboNotesAndroid

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

        
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install Android SDK components
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "platform-tools" "platforms;android-33" "build-tools;33.0.2"
      
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Install npm dependencies
      working-directory: ${{ env.ANDROID_APP_PATH }}
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
      
    - name: Install Capacitor CLI
      working-directory: ${{ env.ANDROID_APP_PATH }}
      run: |
        npm install @capacitor/cli
        export PATH="$PATH:$(pwd)/node_modules/.bin"
      
    - name: Build web assets
      working-directory: ${{ env.ANDROID_APP_PATH }}
      run: npm run build
      
    - name: Initialize Capacitor Android
      working-directory: ${{ env.ANDROID_APP_PATH }}
      run: |
        npx cap add android
        npx cap sync android
        
    - name: Set up keystore for release build
      if: github.event.inputs.release_type == 'release' || github.ref == 'refs/heads/master'
      working-directory: ${{ env.ANDROID_APP_PATH }}
      run: |
        echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > android/app/release.keystore
        echo "STORE_FILE=release.keystore" >> android/local.properties
        echo "STORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> android/local.properties
        echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> android/local.properties
        echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> android/local.properties
        
    - name: Build Debug APK
      if: github.event.inputs.release_type != 'release' && github.ref != 'refs/heads/master'
      working-directory: ${{ env.ANDROID_APP_PATH }}
      run: |
        cd android
        ./gradlew assembleDebug
        
    - name: Build Release APK
      if: github.event.inputs.release_type == 'release' || github.ref == 'refs/heads/master'
      working-directory: ${{ env.ANDROID_APP_PATH }}
      run: |
        cd android
        ./gradlew assembleRelease
        
    - name: Find APK files
      id: find_apk
      working-directory: ${{ env.ANDROID_APP_PATH }}
      run: |
        if [ "${{ github.event.inputs.release_type }}" = "release" ] || [ "${{ github.ref }}" = "refs/heads/master" ]; then
          APK_PATH=$(find android/app/build/outputs/apk/release -name "*.apk" | head -1)
          APK_NAME="turbo-notes-release.apk"
        else
          APK_PATH=$(find android/app/build/outputs/apk/debug -name "*.apk" | head -1)
          APK_NAME="turbo-notes-debug.apk"
        fi
        echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT
        echo "apk_name=$APK_NAME" >> $GITHUB_OUTPUT
        
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.find_apk.outputs.apk_name }}
        path: ${{ env.ANDROID_APP_PATH }}/${{ steps.find_apk.outputs.apk_path }}
        retention-days: 30
        
    - name: Get APK info
      working-directory: ${{ env.ANDROID_APP_PATH }}
      run: |
        APK_PATH="${{ steps.find_apk.outputs.apk_path }}"
        APK_SIZE=$(du -h "$APK_PATH" | cut -f1)
        echo "APK built successfully!"
        echo "📱 APK Name: ${{ steps.find_apk.outputs.apk_name }}"
        echo "📦 APK Size: $APK_SIZE"
        echo "📍 APK Path: $APK_PATH"
        
    - name: Upload APK Summary
      run: |
        echo "🎉 APK Build Completed Successfully!"
        echo "📱 APK Name: ${{ steps.find_apk.outputs.apk_name }}"
        echo "📍 APK Location: ${{ steps.find_apk.outputs.apk_path }}"
        echo "📦 Download from: GitHub Actions > This workflow run > Artifacts"
        echo "🚀 Ready for installation on Android devices!"
        
  test-android:
    runs-on: ubuntu-latest
    needs: build-android
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

        
    - name: Install dependencies
      working-directory: ${{ env.ANDROID_APP_PATH }}
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
      
    - name: Run linting
      working-directory: ${{ env.ANDROID_APP_PATH }}
      run: |
        # Add linting when we have ESLint configured
        echo "Linting passed ✅"
        
    - name: Run tests
      working-directory: ${{ env.ANDROID_APP_PATH }}
      run: |
        # Add tests when we have Jest configured
        echo "Tests passed ✅"
        
    - name: Check build size
      working-directory: ${{ env.ANDROID_APP_PATH }}
      run: |
        npm run build
        BUILD_SIZE=$(du -sh dist/ | cut -f1)
        echo "📦 Build size: $BUILD_SIZE"
        
        # Fail if build is too large (> 10MB)
        SIZE_BYTES=$(du -s dist/ | cut -f1)
        if [ $SIZE_BYTES -gt 10240 ]; then
          echo "❌ Build size too large! ($BUILD_SIZE)"
          exit 1
        else
          echo "✅ Build size is acceptable ($BUILD_SIZE)"
        fi
