name: Android Build

on:
  push:
    branches: [ master ]
    paths:
      - 'android_app/**'
      - '.github/workflows/android-build.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'android_app/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build APK using Kivy Docker image
      working-directory: android_app
      run: |
        # Use the official Kivy Buildozer Docker image
        # This avoids all the libffi compilation issues
        docker run --rm \
          -v ${{ github.workspace }}/android_app:/home/user/app \
          -w /home/user/app \
          kivy/buildozer:latest \
          buildozer android debug
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: turbo-notes-debug-apk
        path: android_app/bin/*.apk
        retention-days: 30 