name: Android Build

on:
  push:
    branches: [ master ]
    paths:
      - 'android_app/**'
      - '.github/workflows/android-build.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'android_app/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Fallback if Ubuntu 24 issues persist:
    # runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache buildozer global directory
      uses: actions/cache@v3
      with:
        path: ~/.buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('android_app/buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-
          
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential autoconf automake libtool pkg-config \
          unzip zip libffi-dev libssl-dev openjdk-17-jdk \
          git python3-pip cmake zlib1g-dev libncurses5-dev \
          libncursesw5-dev libtinfo6 ccache gettext
          
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer==1.5.0 cython==0.29.36
        
    - name: Build Android APK
      working-directory: android_app
      run: |
        # Export environment variables for autotools
        export ACLOCAL="aclocal -I /usr/share/aclocal"
        export ACLOCAL_PATH="/usr/share/aclocal:${ACLOCAL_PATH}"
        
        # Run libtoolize to ensure libtool macros are available
        libtoolize --force --copy
        
        # Clean previous builds (ignore errors)
        buildozer android clean || true
        
        # Build debug APK
        buildozer android debug --verbose
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: turbo-notes-debug-apk
        path: android_app/.buildozer/android/platform/build-*/*/bin/*.apk
        retention-days: 30 